name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: '22'

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building release for version: $VERSION"

      - name: Check if release already exists
        id: check_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: `${{ steps.get_version.outputs.VERSION }}`
              });
              console.log(`Release v${{ steps.get_version.outputs.VERSION }} already exists`);
              core.setFailed(`Release v${{ steps.get_version.outputs.VERSION }} already exists`);
              return;
            } catch (error) {
              if (error.status === 404) {
                console.log(`No existing release for v${{ steps.get_version.outputs.VERSION }}`);
                return false;
              }
              throw error;
            }

      - name: Exit if release exists
        if: steps.check_release.outputs.result == 'true'
        run: |
          echo "Release ${{ steps.get_version.outputs.VERSION }} already exists. Exiting."
          exit 1

      - name: Install Dependencies
        if: steps.check_release.outputs.result != 'true'
        run: npm install

      - name: Build Repo
        if: steps.check_release.outputs.result != 'true'
        run: |
          npm run build:prod

      - name: Prepare Signing Certificates
        if: steps.check_release.outputs.result != 'true'
        run: |
          mkdir -p build
          echo "${{ secrets.APPLE_CERT }}" | base64 --decode > build/apple.cer
          # echo "${{ secrets.WINDOWS_CERT }}" | base64 --decode > build/windows.cer
          echo "${{ secrets.APPLE_NOTARIZATION_PRIVATE_KEY }}" > AuthKey_W442ZA3W3A.p8

      - name: Setup build environment
        if: steps.check_release.outputs.result != 'true'
        run: |
          npm run make:prod
        env:
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}

      - name: Run Conveyor for Release Build
        if: steps.check_release.outputs.result != 'true'
        uses: hydraulic-software/conveyor/actions/build@v18.1
        env:
          APPLE_ASP: ${{ secrets.APPLE_ASP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SITE_RELEASE_TOKEN: ${{ secrets.SITE_RELEASE_TOKEN }}
          NODE_ENV: production
          ENV: production
          MODE: production
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
          APPLE_NOTARIZATION_ISSUER_ID: ${{ secrets.APPLE_NOTARIZATION_ISSUER_ID }}
          APPLE_NOTARIZATION_KEY_ID: ${{ secrets.APPLE_NOTARIZATION_KEY_ID }}
          APPLE_NOTARIZATION_PRIVATE_KEY: ${{ secrets.APPLE_NOTARIZATION_PRIVATE_KEY }}
          APPLE_NOTARIZATION_PRIVATE_KEY_PATH: AuthKey_W442ZA3W3A.p8
          MAC_CERTIFICATE_PATH: build/apple.cer
          # WINDOWS_CERTIFICATE_PATH: build/windows.cer
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          extra_flags: -f conveyor.release.conf
          agree_to_license: 1

      - name: Restore Original Node Modules
        if: steps.check_release.outputs.result != 'true'
        run: |
          echo "🔄 Restoring original node_modules..."
          if [ -d "node_modules.bk" ]; then
            # Remove any node_modules directory that might have been created
            if [ -d "node_modules" ]; then
              rm -rf node_modules
            fi
            mv node_modules.bk node_modules
            echo "✅ Node modules restored successfully"
          else
            echo "⚠️ Warning: node_modules.bk not found for restoration"
          fi
