name: Version Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create Release for Version
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: '22'

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: Install Dependencies
        run: npm install

      - name: Build Repo
        run: |
          npm run build:prod

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Prepare Signing Certificates
        run: |
          mkdir -p build
          echo "${{ secrets.APPLE_CERT }}" | base64 --decode > build/developerID_application.cer
          echo "${{ secrets.SPARKLE_KEY }}" | base64 --decode > sparkle.key

      - name: Setup build environment
        run: |
          npm run make:beta

      - name: Update package.json with beta version
        run: |
          # Update package.json with the beta version using npm pkg
          npm pkg set version="${{ steps.get_version.outputs.VERSION }}"

      # Check if a release already exists
      - name: Check for existing release
        id: check_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: context.ref.replace('refs/tags/', '')
              });
              return true;
            } catch (error) {
              if (error.status === 404) return false;
              throw error;
            }
        continue-on-error: true

      - name: Run Conveyor for Beta Build
        uses: hydraulic-software/conveyor/actions/build@v17.0
        env:
          APPLE_ASP: ${{ secrets.APPLE_ASP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SITE_RELEASE_TOKEN: ${{ secrets.SITE_RELEASE_TOKEN }}
          NODE_ENV: production
          ENV: production
          MODE: production
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          extra_flags: -f conveyor.release.conf
          agree_to_license: 1

      - name: Restore Original Node Modules
        run: |
          echo "🔄 Restoring original node_modules..."
          if [ -d "node_modules.bk" ]; then
            # Remove any node_modules directory that might have been created
            if [ -d "node_modules" ]; then
              rm -rf node_modules
            fi
            mv node_modules.bk node_modules
            echo "✅ Node modules restored successfully"
          else
            echo "⚠️ Warning: node_modules.bk not found for restoration"
          fi
